### ISSUE TITLE
class="form-horizontal" not getting applied on json-schema-form ??

### ISSUE THREAD

**Issue by sandeep048** [json-schema-form/angular-schema-form#785]
I cannot get the form to style as expected. I would like the control labels align to the left and the form elements to the right. Highly appreciate if I can get hold of a working example.

**Comment by sandeep048** [comment]
Some thing like this. Horizontal form layout?

![image](https://cloud.githubusercontent.com/assets/500899/19425357/23f75e24-944f-11e6-9e29-f7e0f3074d91.png)

**Comment by Anthropic** [comment]
@sandeep048 you use CSS to change layout, for example this will set your label and the control to inline instead of acting like a block which is half the way there.
```css
.form-group label {
    display: inline-block;
    width: 170px;
}
.form-control {
    display: inline-block;
    width: 330px;
}
```
You will find much better CSS help on Stack Overflow than here though, so i suggest asking for styling help there with the source output from your form.
